In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
df=pd.read_csv("titanic.csv")

In [6]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
df.drop(["PassengerId","Name","Ticket"],axis=1,inplace=True)

In [9]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [10]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [11]:
mean_age=round(df["Age"].mean())

In [12]:
df["Age"]=df["Age"].fillna(mean_age)

In [13]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [16]:
df["Cabin"]=df["Cabin"].fillna(method="ffill")
df["Embarked"]=df["Embarked"].fillna(method="ffill")

In [17]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Cabin       0
Embarked    0
dtype: int64

In [18]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   C85        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250  C123        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   E46        S

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
encoder=LabelEncoder()

In [22]:
df["Sex"]=encoder.fit_transform(df["Sex"])
df["Cabin"]=encoder.fit_transform(df["Cabin"])
df["Embarked"]=encoder.fit_transform(df["Embarked"])

In [23]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0         0       3    1  22.0      1      0   7.2500     81         2
1         1       1    0  38.0      1      0  71.2833     81         0
2         1       3    0  26.0      0      0   7.9250     55         2
3         1       1    0  35.0      1      0  53.1000     55         2
4         0       3    1  35.0      0      0   8.0500    129         2

In [24]:
X=df.drop("Survived",axis=1)

In [25]:
y=df[["Survived"]]

In [26]:
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0       3    1  22.0      1      0   7.2500     81         2
1       1    0  38.0      1      0  71.2833     81         0
2       3    0  26.0      0      0   7.9250     55         2
3       1    0  35.0      1      0  53.1000     55         2
4       3    1  35.0      0      0   8.0500    129         2

In [27]:
col=X.columns

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
scaler=StandardScaler()

In [30]:
X=scaler.fit_transform(X)

In [31]:
X=pd.DataFrame(X,columns=col)

In [ ]:
X.head()

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [35]:
X_train.shape,X_test.shape

((712, 8), (179, 8))

 #### Logistic Regression

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
model=LogisticRegression()

In [39]:
parameters={"C":[0.01,0.1,1,2,5,10]}

In [40]:
from sklearn.model_selection import GridSearchCV

In [41]:
cv=GridSearchCV(model,parameters,cv=5)

In [42]:
cv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 2, 5, 10]})

In [43]:
cv.best_estimator_

LogisticRegression(C=0.01)

In [44]:
model=cv.best_estimator_

In [45]:
model.score(X_train,y_train)

0.8061797752808989

In [46]:
model.score(X_test,y_test)

0.8100558659217877

In [47]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [48]:
y_predicted=model.predict(X_test)

In [49]:
accuracy_score(y_test,y_predicted)

0.8100558659217877

In [50]:
cnf=confusion_matrix(y_test,y_predicted)

In [51]:
cnf

array([[97, 13],
       [21, 48]], dtype=int64)

### RandomForestClassifier

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
model1=RandomForestClassifier()

In [54]:
parameters1={"n_estimators":[1,5,10,25,50,100],
            "criterion":["gini","entopy"],
            "max_depth":[10,20,50,100]}

In [55]:
cv1=GridSearchCV(model1,parameters1,cv=5)

In [56]:
cv1.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entopy'],
                         'max_depth': [10, 20, 50, 100],
                         'n_estimators': [1, 5, 10, 25, 50, 100]})

In [57]:
cv1.best_estimator_

RandomForestClassifier(max_depth=20)

In [60]:
model1=cv1.best_estimator_

In [61]:
model1.score(X_train,y_train)

1.0

In [62]:
model1.score(X_test,y_test)

0.8324022346368715

In [63]:
y_predicted1=model1.predict(X_test)

In [64]:
accuracy_score(y_test,y_predicted1)

0.8324022346368715

In [65]:
confusion_matrix(y_test,y_predicted)

array([[97, 13],
       [21, 48]], dtype=int64)

### Decision Tree

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
model2=DecisionTreeClassifier()

In [68]:
parameters2={"max_depth":[10,20,50,75,100],
            "min_samples_split":[1,2,5,10,20,25],
            "min_samples_leaf":[1,2,5,8,10]}

In [69]:
cv2=GridSearchCV(model2,parameters2,cv=5)

In [70]:
cv2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [10, 20, 50, 75, 100],
                         'min_samples_leaf': [1, 2, 5, 8, 10],
                         'min_samples_split': [1, 2, 5, 10, 20, 25]})

In [71]:
cv2.best_estimator_

DecisionTreeClassifier(max_depth=10, min_samples_leaf=8)

In [72]:
model2=cv2.best_estimator_

In [73]:
model2.score(X_train,y_train)

0.8637640449438202

In [74]:
model2.score(X_test,y_test)

0.8603351955307262

In [75]:
y_predicted2=model2.predict(X_test)

In [76]:
accuracy_score(y_predicted2,y_test)

0.8603351955307262

In [77]:
cnf2=confusion_matrix(y_test,y_predicted2)

In [78]:
cnf2

array([[100,  10],
       [ 15,  54]], dtype=int64)

#### GaussianNB

In [79]:
from sklearn.naive_bayes import GaussianNB

In [81]:
model3=GaussianNB()

In [82]:
parameters3={"priors":[None]}

In [83]:
cv3=GridSearchCV(model3,parameters3,cv=5)

In [84]:
cv3.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=GaussianNB(), param_grid={'priors': [None]})

In [85]:
cv3.best_estimator_

GaussianNB()

In [88]:
model3=cv3.best_estimator_

In [89]:
model3.score(X_train,y_train)

0.7879213483146067

In [90]:
model3.score(X_test,y_test)

0.7877094972067039

### SVC

In [94]:
from sklearn.svm import SVC

In [95]:
model4=SVC()

In [96]:
parameters4={"C":[1,2,5,10,20,50,75,100],
            "kernel":["rbf","linear"]}

In [97]:
cv4=GridSearchCV(model4,parameters4,cv=5)

In [98]:
cv4.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 2, 5, 10, 20, 50, 75, 100],
                         'kernel': ['rbf', 'linear']})

In [99]:
cv4.best_estimator_

SVC(C=2)

In [100]:
model4=cv4.best_estimator_

In [101]:
model4.score(X_train,y_train)

0.8469101123595506

In [102]:
model.score(X_test,y_test)

0.8100558659217877